#!/usr/bin/env bash
# prepare.sh - build a VMS-ready lighttpd source tree in staging/<name>-<version>/
#
#   1. fetch + verify the upstream tarball
#   2. extract it, apply patches/series, lay overlay/ over the top
#
# There is no host- or node-side configure: overlay/vmsport/config_vms.h is
# maintained by hand from the Phase 0 probes (docs/DECISIONS.md D3), and
# vmsport/BUILD.COM + DESCRIP.MMS compile it with VSI C.
#
# Nothing in staging/ is ever edited by hand: fix things in patches/ or overlay/.
set -euo pipefail

top=$(cd "$(dirname "$0")/.." && pwd)
. "$top/upstream.conf"
name=$UPSTREAM_NAME-$UPSTREAM_VERSION
tarball=$top/cache/$(basename "$UPSTREAM_URL")
stage=$top/staging/$name

step() { echo "prepare: $*"; }
die() { echo "prepare: error: $*" >&2; exit 1; }

"$top/tools/fetch.sh" >/dev/null

step "extracting $name"
rm -rf "$stage"; mkdir -p "$top/staging"
tar -xJf "$tarball" -C "$top/staging"
[ -d "$stage" ] || die "tarball did not unpack to $stage"

while read -r p; do
    case $p in ''|'#'*) continue ;; esac
    step "patch $p"
    patch -d "$stage" -p1 -s --no-backup-if-mismatch -F0 < "$top/patches/$p" ||
        die "patch $p does not apply cleanly"
done < "$top/patches/series"

# overlay/ may only add files; changes to upstream files belong in patches/.
(cd "$top/overlay" && find . -type f ! -name .keep) | while read -r f; do
    [ -e "$stage/$f" ] && die "overlay/$f would replace an upstream file; use a patch"
    true
done
(cd "$top/overlay" && find . -type f ! -name .keep -print0 | xargs -0r cp --parents -t "$stage/")

mkdir -p "$stage/vmsport"
printf 'VERSION=%s\nKIT_VERSION=%s-vms%s\n' "$UPSTREAM_VERSION" "$UPSTREAM_VERSION" \
    "$VMS_PATCH_LEVEL" > "$stage/vmsport/version.env"

# Version macros that CMake writes into config.h (src/CMakeLists.txt:
# LIGHTTPD_VERSION_ID 0x104<patch>); our config.h includes this file.
patchlevel=${UPSTREAM_VERSION##*.}
cat > "$stage/src/vms_version.h" <<EOF
/* Generated by tools/prepare.sh from upstream.conf - do not edit. */
#define LIGHTTPD_VERSION_ID 0x104$patchlevel
#define PACKAGE_VERSION "$UPSTREAM_VERSION-vms$VMS_PATCH_LEVEL"
EOF

# The config file parser is generated by lemon at build time; run it here
# with the host compiler, as CMake does when cross-compiling
# (scripts/cmake/LighttpdMacros.cmake LEMON_PARSER).
step "lemon: configparser.c"
lemon=$top/cache/lemon
cc -O1 -o "$lemon" "$stage/src/lemon.c" || die "cannot build lemon with the host cc"
"$lemon" -q -d"$stage/src" -T"$stage/src/lempar.c" "$stage/src/configparser.y" ||
    die "lemon failed"
[ -f "$stage/src/configparser.c" ] && [ -f "$stage/src/configparser.h" ] ||
    die "lemon did not write configparser.c/.h"
# --- PCSI kit inputs (vmsport/kit/MAKE_KIT.COM builds the kit on each node) --
step "PCSI kit inputs"
kit=$stage/vmsport/kit
: "${KIT_PRODUCER:=ISSINOHO}"
# lighttpd 1.4.85 with VMS patch level 1 is PCSI V1.4-85E1 (update = third
# part, ECO = our patch level), as the sibling kits do.
IFS=. read -r major minor update _ <<< "$UPSTREAM_VERSION"
pcsiversion="V$major.$minor-${update:-0}E$VMS_PATCH_LEVEL"
kitversion="$UPSTREAM_VERSION-vms$VMS_PATCH_LEVEL"
subst() {
    sed -e "s/@PRODUCER@/$KIT_PRODUCER/g" -e "s/@BASE@/$1/g"         -e "s/@PCSIVERSION@/$pcsiversion/g" -e "s/@VERSION@/$UPSTREAM_VERSION/g"         -e "s/@KITVERSION@/$kitversion/g" -e "s/@ARCH@/$2/g"
}
lc=$(echo "$KIT_PRODUCT" | tr A-Z a-z)
for base in I64VMS X86VMS; do
    subst $base "" < "$kit/$lc.pcsi\$desc_template" > "$kit/PRODUCT-$base.PCSI\$DESC"
    subst $base "" < "$kit/$lc.pcsi\$text_template" > "$kit/PRODUCT-$base.PCSI\$TEXT"
done
rm -f "$kit/$lc.pcsi\$desc_template" "$kit/$lc.pcsi\$text_template"
subst "" "IA64 and x86-64" < "$kit/readme.vms" > "$kit/README.VMS"; rm -f "$kit/readme.vms"
# shared pieces: the PHP pool and its ini templates, phpBB's rules,
# upstream's MIME types
cp "$stage/vmsport/php/php_pool.com" "$kit/PHP_POOL.COM"
cp "$stage/vmsport/php/php.ini" "$kit/PHP.INI"
cp "$stage/vmsport/php/php-vsi80.ini" "$kit/PHP-VSI80.INI"
cp "$stage/vmsport/conf/phpbb.conf" "$kit/PHPBB.CONF"
cp "$stage/doc/config/conf.d/mime.conf" "$kit/MIME.CONF"
cp "$stage/COPYING" "$kit/COPYING."
cp "$stage/NEWS" "$kit/NEWS."
printf 'KIT_PRODUCER=%s
KIT_PRODUCT=%s
PCSI_VERSION=%s
KIT_VERSION=%s
' "$KIT_PRODUCER"     "$KIT_PRODUCT" "$pcsiversion" "$kitversion" > "$kit/kit.env"
step "staged $stage"
