#!/usr/bin/env bash
# prepare.sh - build a VMS-ready lighttpd source tree in staging/<name>-<version>/
#
#   1. fetch + verify the upstream tarball
#   2. extract it, apply patches/series, lay overlay/ over the top
#
# There is no host- or node-side configure: overlay/vmsport/config_vms.h is
# maintained by hand from the Phase 0 probes (docs/DECISIONS.md D3), and
# vmsport/BUILD.COM + DESCRIP.MMS compile it with VSI C.
#
# Nothing in staging/ is ever edited by hand: fix things in patches/ or overlay/.
set -euo pipefail

top=$(cd "$(dirname "$0")/.." && pwd)
. "$top/upstream.conf"
name=$UPSTREAM_NAME-$UPSTREAM_VERSION
tarball=$top/cache/$(basename "$UPSTREAM_URL")
stage=$top/staging/$name

step() { echo "prepare: $*"; }
die() { echo "prepare: error: $*" >&2; exit 1; }

"$top/tools/fetch.sh" >/dev/null

step "extracting $name"
rm -rf "$stage"; mkdir -p "$top/staging"
tar -xJf "$tarball" -C "$top/staging"
[ -d "$stage" ] || die "tarball did not unpack to $stage"

while read -r p; do
    case $p in ''|'#'*) continue ;; esac
    step "patch $p"
    patch -d "$stage" -p1 -s --no-backup-if-mismatch -F0 < "$top/patches/$p" ||
        die "patch $p does not apply cleanly"
done < "$top/patches/series"

# overlay/ may only add files; changes to upstream files belong in patches/.
(cd "$top/overlay" && find . -type f ! -name .keep) | while read -r f; do
    [ -e "$stage/$f" ] && die "overlay/$f would replace an upstream file; use a patch"
    true
done
(cd "$top/overlay" && find . -type f ! -name .keep -print0 | xargs -0r cp --parents -t "$stage/")

mkdir -p "$stage/vmsport"
printf 'VERSION=%s\nKIT_VERSION=%s-vms%s\n' "$UPSTREAM_VERSION" "$UPSTREAM_VERSION" \
    "$VMS_PATCH_LEVEL" > "$stage/vmsport/version.env"

# Version macros that CMake writes into config.h (src/CMakeLists.txt:
# LIGHTTPD_VERSION_ID 0x104<patch>); our config.h includes this file.
patchlevel=${UPSTREAM_VERSION##*.}
cat > "$stage/src/vms_version.h" <<EOF
/* Generated by tools/prepare.sh from upstream.conf - do not edit. */
#define LIGHTTPD_VERSION_ID 0x104$patchlevel
#define PACKAGE_VERSION "$UPSTREAM_VERSION-vms$VMS_PATCH_LEVEL"
EOF

# The config file parser is generated by lemon at build time; run it here
# with the host compiler, as CMake does when cross-compiling
# (scripts/cmake/LighttpdMacros.cmake LEMON_PARSER).
step "lemon: configparser.c"
lemon=$top/cache/lemon
cc -O1 -o "$lemon" "$stage/src/lemon.c" || die "cannot build lemon with the host cc"
"$lemon" -q -d"$stage/src" -T"$stage/src/lempar.c" "$stage/src/configparser.y" ||
    die "lemon failed"
[ -f "$stage/src/configparser.c" ] && [ -f "$stage/src/configparser.h" ] ||
    die "lemon did not write configparser.c/.h"
step "staged $stage"
