/* plugin-static.h - modules linked into lighttpd for OpenVMS (LIGHTTPD_STATIC).
   plugin.c includes this twice, with PLUGIN_INIT defined differently.
   Keep the list in step with MODULES in vmsport/BUILD.COM. */
PLUGIN_INIT(mod_rewrite)
PLUGIN_INIT(mod_redirect)
PLUGIN_INIT(mod_access)
PLUGIN_INIT(mod_alias)
PLUGIN_INIT(mod_indexfile)
PLUGIN_INIT(mod_staticfile)
PLUGIN_INIT(mod_setenv)
PLUGIN_INIT(mod_expire)
PLUGIN_INIT(mod_simple_vhost)
PLUGIN_INIT(mod_evhost)
PLUGIN_INIT(mod_fastcgi)
PLUGIN_INIT(mod_scgi)
PLUGIN_INIT(mod_accesslog)
PLUGIN_INIT(mod_deflate)
PLUGIN_INIT(mod_dirlisting)
PLUGIN_INIT(mod_extforward)
PLUGIN_INIT(mod_proxy)
PLUGIN_INIT(mod_status)
PLUGIN_INIT(mod_h2)
PLUGIN_INIT(mod_openssl)
